* Learn about Scripting
[[https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting][Dota 2 Scripting]]
[[http://www.lua.org/manual/5.3/][Lua Reference]]

Lua things may go in /game. Must other stuff in /game is not helpful.

https://github.com/Lattyware/itemdraft (try this out)

This is the stuff: https://github.com/Lattyware/itemdraft/blob/master/game/dota_addons/itemdraft/scripts/vscripts/draft.lua

** What runs where?
There is Lua on both client and server.
script_attach_debugger cl_script_attach_debugger

Vconsole2 is what runs in the workshop tools. What does it have access to?

My scripts aren't going in. Bleh.

** Panorama
This is an XML/CSS/JS UI framework.

Panels are elements.

*** Lua
Can use Lua to create the UI dynamically instead.

*** Custom loading screen
custom_loading_screen.xml

*** Valve UI
[[https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Panorama/Valve_Provided_UI][Valve UI]] may have some helpful bits?

** Libraries
Considering using the Barebones timers library?

** Empty Abilities
Found in [[https://github.com/Lattyware/itemdraft/blob/master/game/dota_addons/itemdraft/scripts/npc/npc_heroes_custom.txt][npc_heroes_custom.txt]]:

(Why these?)

"Ability1"         "invoker_empty1"
"Ability2"         "invoker_empty2"
"Ability3"         "doom_bringer_empty1"
"Ability4"         "doom_bringer_empty2"
"Ability5"         "wisp_empty1"
"Ability6"         "wisp_empty2"

** Localization
game\dota_addons\card_draft\resource\addon_english.txt
game\dota_addons\card_draft\panorama\localization\addon_english.txt (does this come from content originally?)

** addon_game_mode.lua
require other files.

GameMode:InitGameMode()

** vscripts/gamemode.lua
Provides some hooks:

=GameRules:EnableCustomGameSetupAutoLaunch(false)= iniside InitGameMode

=function GameMode:OnAllPlayersLoaded()= for hero selection

=GameMode:OnHeroInGame(hero)= first spawn - can change abilities here?

* Plan
** Customize hero choice screen
Implement function GameMode:OnAllPlayersLoaded()

hide the hero choice screen.

Break here.

=PauseGame(true)= during the draft, =PauseGame(false)= when it's done.

** Device to assign starting hands
Deal each player the right number of each type of cards, ensuring no overlap.


** Display cards and choices
** Pass cards around after players all made their choice

** Card eligibility and automatic plays

** Timer and random plays

** English Localization
Custom game name should appear in the right place.

* Future Plans
